// apps/steer-login/components/Button.tsx
type ButtonProps = {
    children: React.ReactNode;
    onClick: () => void;
    className?: string;
    variant?: 'primary' | 'secondary';
    disabled?: boolean;
};

export default function Button({ children, onClick, className = '', variant = 'primary', disabled = false }: ButtonProps) {


    const buttonClass = `box-border flex items-center justify-center text-sm font-semibold uppercase px-4 py-2 border ${className}`;

    return (
        <button
            disabled={disabled}
            onClick={onClick}
            className={`${buttonClass} ${variant === 'primary'
                ? 'border-neutral-200 bg-neutral-200 hover:enabled:bg-neutral-50 text-content-inverse'
                : 'border-neutral-400 hover:enabled:border-neutral-200 text-content-primary'}`}
        >
            {children}
        </button>
    );
}

// apps/cognitic-website/src/lib/shared/components/Button.svelte
<script lang="ts">
  export let disabled = false;
  export let as: string = 'button';
  export let size: 'small' | 'medium' | 'large' | 'custom' = 'small';
  export let textSize: 'small' | 'large' = 'small';
  export let variant: 'primary' | 'secondary' | 'tertiary' = 'primary';

  function remainingProps() {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { as, size, variant, ...rest } = $$props;
    delete rest.class;
    return rest;
  }
</script>

<svelte:element
  this={as}
  on:click
  class:cursor-not-allowed={disabled}
  class:body-small-plus={textSize === 'small'}
  class:body-regular-plus={textSize === 'large'}
  class={`box-border flex items-center justify-center uppercase
    ${variant}
    ${size}
    ${$$props.class}
  `}
  {...remainingProps()}
>
  <slot>Button</slot>
</svelte:element>

<style lang="postcss">
  .secondary,
  .tertiary,
  .error {
    @apply border;
  }

  .primary:not(:disabled) {
    @apply bg-primary text-content-inverse hover:bg-primary-lighter;
  }
  .primary:disabled {
    @apply bg-background-primaryDisabled text-background-primary;
  }
  .secondary:not(:disabled) {
    @apply border-primary text-content-primary hover:bg-primary-lighter hover:text-content-inverse;
  }
  .secondary:disabled {
    @apply border-stroke-secondary text-content-secondary;
  }
  .tertiary:not(:disabled) {
    @apply border-stroke-secondary text-content-secondary hover:border-content-secondary;
  }
  .tertiary:disabled {
    @apply border-stroke-secondary text-content-tertiary;
  }
  .error:not(:disabled) {
    @apply bg-error text-content-inverse hover:bg-error-lighter;
  }
  .error:disabled {
    @apply border-error bg-error text-content-inverse opacity-40;
  }

  .small {
    @apply h-6 px-2 py-1;
  }
  .medium {
    @apply h-8 px-2 py-1;
  }
  .large {
    @apply h-12 px-3 py-2;
  }
</style>
